apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xgo9mvxwd-python 
  janus-idp.io/tekton: xgo9mvxwd-python
  backstage.io/kubernetes-id: xgo9mvxwd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xgo9mvxwd-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  