apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xgo9mvxwd-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:345488b33d51dd8634a59be51c2a5ef12e94143d@sha256:e83191e2e49d24d9de3ad667813e9a30fcc94f29a9a3c7dd79615cd2ee19ba87
          name: container-image
