apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xgo9mvxwd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xgo9mvxwd-python 
  name: xgo9mvxwd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xgo9mvxwd-python 
